backend:
  name: github
  repo: cizzu/website # Path to your GitLab repository

media_folder: "static/images/upload" # Folder where user uploaded files should go
public_folder: "/images/upload"

# media_library:
#   name: cloudinary
#   config:
#     cloud_name: tendabiru
#     api_key: 444617156827818
#     default_transformations:
#       -   - fetch_format: auto
#             width: 0.6
#             quality: 20

media_library:
  name: uploadcare
  config:
    publicKey: f855db64f67de7e3373a

collections:
  - name: "post"
    label: "Post"
    folder: content/post
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Keywords", name: "keywords", widget: "list" }
      - { label: "Thumbnail", name: "thumbnailImage", widget: "string" }
      - { label: "Thumbnail Positioin", name: "thumbnailImagePosition", widget: "select", options: ["top", "left", "right"], default: "top" }
      - { label: "Cover Image", name: "coverImage", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
